version: "3.1"


services:
  dashboard:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BRANCH=main
    image: "gdsc-admin-dashboard"
    ports:
      - "3000:3000"
    command: yarn start
